server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
#    url: jdbc:mysql://english-center-db-ntphong-db.c.aivencloud.com:19323/english_center_db?useSSL=true&verifyServerCertificate=false
#    username: avnadmin
#    password: AVNS_pHueFS54Wi1YixZLxLw
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/english_center_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off

logging:
  level:
    root: warn

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 360000 # in second
  refreshable-duration: 36000 # in seconds

cloudinary:
  cloud-name: dnsve3y1o
  api-key: 581348459133918
  api-secret: VgZe7nNcuRFcWf2Yv-aB6Rwobrw