server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/english_center_db"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off

logging:
  level:
    root: warn

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
