services:
  springboot-app:
    build: .
    container_name: spring-app-postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://dpg-d196evjuibrs73bshobg-a.singapore-postgres.render.com:5432/english_center_db
      DB_USERNAME: phong
      DB_PASSWORD: t2NkwYCMZMGfkVdxbA1rSdsB83h6bpbY
