package vn.edu.actvn.server.constant;

import lombok.Getter;
import vn.edu.actvn.server.service.RoleService;

@Getter
public enum Permission {
    // USER permissions
    USER_READ("USER_READ"),
    USER_CREATE("USER_CREATE"),
    USER_UPDATE("USER_UPDATE"),
    USER_DELETE("USER_DELETE"),

    // AUTH permissions


    // CLASS permissions
    CLASS_READ("CLASS_READ"),
    CLASS_READ_ALL("CLASS_READ_ALL"),
    CLASS_CREATE("CLASS_CREATE"),
    CLASS_UPDATE("CLASS_UPDATE"),
    CLASS_DELETE("CLASS_DELETE"),

    // STUDENT permissions
    STUDENT_READ("STUDENT_READ"),
    STUDENT_READ_ALL("STUDENT_READ_ALL"),
    STUDENT_CREATE("STUDENT_CREATE"),
    STUDENT_UPDATE("STUDENT_UPDATE"),
    STUDENT_DELETE("STUDENT_DELETE"),

    // TEACHER permissions
    TEACHER_READ("TEACHER_READ"),
    TEACHER_READ_ALL("TEACHER_READ_ALL"),
    TEACHER_CREATE("TEACHER_CREATE"),
    TEACHER_UPDATE("TEACHER_UPDATE"),
    TEACHER_DELETE("TEACHER_DELETE"),

    // PARENT permissions
    PARENT_READ("PARENT_READ"),
    PARENT_READ_ALL("PARENT_READ_ALL"),
    PARENT_CREATE("PARENT_CREATE"),
    PARENT_UPDATE("PARENT_UPDATE"),
    PARENT_DELETE("PARENT_DELETE"),

    // ATTENDANCE permissions
    ATTENDANCE_READ("ATTENDANCE_READ"),
    ATTENDANCE_CREATE("ATTENDANCE_CREATE"),
    ATTENDANCE_UPDATE("ATTENDANCE_UPDATE"),

    // PAYMENT permissions
    PAYMENT_READ("PAYMENT_READ"),
    PAYMENT_CREATE("PAYMENT_CREATE"),
    PAYMENT_UPDATE("PAYMENT_UPDATE"),

    // TUITION_FEE permissions
    TUITION_FEE_READ("TUITION_FEE_READ"),
    TUITION_FEE_READ_ALL("TUITION_FEE_READ_ALL"),
    TUITION_FEE_CREATE("TUITION_FEE_CREATE"),
    TUITION_FEE_UPDATE("TUITION_FEE_UPDATE"),
    TUITION_FEE_DELETE("TUITION_FEE_DELETE"),

    // ROLE permissions
    ROLE_READ("ROLE_READ"),
    ROLE_CREATE("ROLE_CREATE"),
    ROLE_UPDATE("ROLE_UPDATE"),
    ROLE_DELETE("ROLE_DELETE"),

    // IMAGE permissions
    IMAGE_AVATAR_UPLOAD("IMAGE_AVATAR_UPLOAD"),
    IMAGE_BANNER_UPLOAD("IMAGE_BANNER_UPLOAD"),

    // BANNER permissions
    BANNER_READ("BANNER_READ"),
    BANNER_READ_ALL("BANNER_READ_ALL"),
    BANNER_CREATE("BANNER_CREATE"),
    BANNER_UPDATE("BANNER_UPDATE"),
    BANNER_DELETE("BANNER_DELETE")

    ;

    private final String permission;

    Permission(String permission) {
        this.permission = permission;
    }

}
